### ISSUE TITLE
Error in script work after change 

### ISSUE THREAD

**Issue by VovaVoms** [sebastian-philipp/btrfs-swapon#2]
Error in script work after change that mentioned below!
Expecting "`сhmod 0600 $swapname`" instead of "`сhmod 0600 /swap`"

> Commits on Jul 23, 2017  @lub
> change permissions on swap file
> lub committed on GitHub 25 days ago
> 
> +chmod 0600 /swap

https://github.com/sebastian-philipp/btrfs-swapon/blob/3f0f9da86c86f0d0281558cc010fdef8ce54a232/btrfs-swapon#L33

**Comment by sebastian-philipp** [comment]
I guess this can be closed after your PR?

**Comment by VovaVoms** [comment]
Yes!
This works fine (tested on several laptops with small ssd).

P.S. Sorry for long response!
