### ISSUE TITLE
btrfs added support for swapfiles

### ISSUE THREAD

**Issue by chpio** [sebastian-philipp/btrfs-swapon#6]
> From kernel 5.0+ btrfs have native swap files support, but with some limitations. Swap file - must be fully allocated as NOCOW with no compression on one device. 
>
> -- <https://btrfs.wiki.kernel.org/index.php/FAQ#Does_btrfs_support_swap_files.3F>

> Btrfs has not allowed swap files since commit 35054394c4b3 ("Btrfs: stop providing a bmap operation to avoid swapfile corruptions"). However, now that the proper restrictions are in place, Btrfs can support swap files through the swap file a_ops, similar to iomap in commit 67482129cdab ("iomap: add a swapfile activation function").
>
> For Btrfs, activation needs to make sure that the file can be used as a swap file, which currently means that it must be fully allocated as NOCOW with no compression on one device. It must also do the proper tracking so that ioctls will not interfere with the swap file. Deactivation clears this tracking. 
>
> -- <https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ed46ff3d423780fa5173b38a844bf0fdb210a2a7>

**Comment by sebastian-philipp** [comment]
Updated the readme. Thanks for the info!
